name: Build Zenoh Docker Image

on:
  push:
    branches:
      - main  # 或者您希望监控的分支
  pull_request:
    branches:
      - main  # 或者您希望监控的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t zenoh_env .

    - name: Push Docker Image (Optional)
      if: github.ref == 'refs/heads/main'  # 仅在 main 分支推送时执行
      run: |
        docker tag zenoh_env registry.lyy520.fun:8443/zenoh_env:latest
        docker push registry.lyy520.fun:8443/zenoh_env:latest
